### PR TITLE
memoize parseMarkdown

### PR DESCRIPTION
**Pull request by Fil**
This will make operations such as (re)indexation (#543) and lazy config (#695) much more usable in preview, and might save a few seconds during build (instead of parsing each file 2 or 3 times, we'd do it only once), for example to assist with last-modified (#699) and hashing (#758).

To make sure that we don't inflate the memory requirements I'm capping this arbitrarily to a store that has a maximum of 16^4 shortCode keys — as long as the percentage of conflicts is small the impact on speed is not going to be a problem. (Note: we take care of checking the full hash before deciding to use the cache, so as not to mix two files which would happen to share the same shortCode slot.)

### CODE REVIEW

**Comment by Fil** [comment]
needs to be revisited after #843

**Comment by Fil** [comment]
mhhh… this might still be useful for #695

**Comment by mbostock** [comment]
I’m guessing we don’t need this anymore after recent optimizations?

**Comment by Fil** [comment]
yes!

**Pull request closed without merging**
