### PR TITLE
hint to "deploy help" in the documentation

### LINKED ISSUE #1105: document --if-missing and --if-stale
https://observablehq.com/framework/deploying should describe these new options introduced in #1042

### PR DESCRIPTION
**Pull request by Fil**
closes #1105

### CODE REVIEW

**Review by mbostock — COMMENTED** [review]
I appreciate the additional documentation, but this feels a little out of place here. I think it would be better to expand the `observable help deploy` output as I mentioned in Slack. We could also have a command reference page, perhaps, though I like the idea that the reference is built-in to the tool itself.

**Comment by Fil** [comment]
Then maybe we just say "call `npm observable help deploy` for more options"?

**Comment by mbostock** [comment]
It’s `npm run observable help deploy`, but yeah. 😅

**Review by mbostock — APPROVED** [review]
Made it a tip, and switched to:

```sh
npm run deploy -- --help
```

**Pull request merged**
