### PR TITLE
Document how to use aq.loadArrow in combination with a file attachment.

### PR DESCRIPTION
**Pull request by Fil**
This question came as a support request.

### CODE REVIEW

**Review by mbostock — COMMENTED** [review]
Does loadArrow return a promise to a table? It would probably better to include the const declaration so that it’s more obvious how to use the loaded table.

**Comment by Fil** [comment]
I've updated the copy with a more complete example.

**Review by mbostock — COMMENTED** [review]
Should we add a `FileAttachment.arquero` method? Presumably it’d be trivial and it makes sense given that `aq` is already part of the standard library.

**Comment by mbostock** [comment]
Superseded by #1509.

**Pull request closed without merging**
