### PR TITLE
fix node imports

### LINKED ISSUE #1224: Bare node imports don’t work in imported local modules
Seems like a pretty major oversight from #1156. This works in Markdown:

````md
```js
import "d3-array";
```
````

But this doesn’t work in a local module (the import isn’t rewritten to `/_node/…`):

```js
import "d3-array";
```

`npm:` imports still work as expected in both places.

### PR DESCRIPTION
**Pull request by mbostock**
Fixes #1224. Easy fix. We just forgot to resolve them. 🤦 Added a test!

### CODE REVIEW

**Review by Fil — APPROVED** [review]

**Comment by Fil** [comment]
I can systematically reproduce the test erroring by calling:

> rm -rf docs/.observablehq/cache && yarn test:mocha:serial

Also it does not error when I isolate the test with `.only`. 

I see the same error with node v21.6.0 and v20.11.1. The error goes away if I `import fetch from "node-fetch"`, so it might be a problem specific to undici.

**Comment by mbostock** [comment]
Thanks for the tip! We were missing a mock.

**Comment by Fil** [comment]
using catch(console.error) I can get a stack trace:

```
npm:d3-array → TypeError: fetch failed
    at node:internal/deps/undici/undici:12345:11
    at async file:///Users/fil/Source/framework/test/build/src/npm.js:197:22 {
  cause: MockNotMatchedError: Mock dispatch not matched for path '/v1/packages/npm/d3-array/resolved': subsequent request to origin https://data.jsdelivr.com was not allowed (net.connect disabled)
      at MockPool.dispatch (/Users/fil/Source/framework/node_modules/undici/lib/mock/mock-utils.js:313:19)
      at [dispatch] (/Users/fil/Source/framework/node_modules/undici/lib/dispatcher/agent.js:105:23)
      at Intercept (/Users/fil/Source/framework/node_modules/undici/lib/interceptor/redirect-interceptor.js:11:16)
      at [Intercepted Dispatch] (/Users/fil/Source/framework/node_modules/undici/lib/dispatcher/dispatcher-base.js:158:12)
      at Agent.dispatch (/Users/fil/Source/framework/node_modules/undici/lib/dispatcher/dispatcher-base.js:179:40)
      at MockAgent.dispatch (/Users/fil/Source/framework/node_modules/undici/lib/mock/mock-agent.js:55:25)
      at node:internal/deps/undici/undici:10929:55
      at new Promise (<anonymous>)
      at dispatch (node:internal/deps/undici/undici:10929:16)
      at httpNetworkFetch (node:internal/deps/undici/undici:10824:73)
      at httpNetworkOrCacheFetch (node:internal/deps/undici/undici:10712:39)
      at httpFetch (node:internal/deps/undici/undici:10545:43)
      at schemeFetch (node:internal/deps/undici/undici:10469:18)
      at node:internal/deps/undici/undici:10342:26
      at mainFetch (node:internal/deps/undici/undici:10361:11)
      at fetching (node:internal/deps/undici/undici:10309:7)
      at fetch (node:internal/deps/undici/undici:10173:20)
      at Object.fetch (node:internal/deps/undici/undici:12344:10)
      at fetch (node:internal/process/pre_execution:336:27)
      at file:///Users/fil/Source/framework/test/build/src/npm.js:197:28
      at resolveNpmVersion (file:///Users/fil/Source/framework/test/build/src/npm.js:209:4)
      at async resolveNpmImport (file:///Users/fil/Source/framework/test/build/src/npm.js:220:19)
      at async file:///Users/fil/Source/framework/test/build/src/resolvers.js:246:412
      at async rewriteImportSource (file:///Users/fil/Source/framework/test/build/src/javascript/transpile.js:61:65)
      at async transpileModule (file:///Users/fil/Source/framework/test/build/src/javascript/transpile.js:71:7)
      at async Context.<anonymous> (file:///Users/fil/Source/framework/test/build/test/javascript/transpile-test.js:191:21) {
    code: 'UND_MOCK_ERR_MOCK_NOT_MATCHED'
  }
}
```

**Comment by Fil** [comment]
👍

**Pull request merged**
